const pageMeta = {
  pl: {
    title: "Smerthnix - strony internetowe dla firm od 2000 zł",
    description:
      "Tworzę nowoczesne strony internetowe dla firm usługowych. Realizacja od 2000 zł, wersja mobilna, Booksy, formularze, SEO i dodatkowe funkcje.",
  },
  ru: {
    title: "Smerthnix - сайты для бизнеса от 2000 zł",
    description:
      "Создаю современные сайты для салонов, услуг и малого бизнеса. Стоимость от 2000 zł: мобильная версия, Booksy, формы, SEO и дополнительные функции.",
  },
  uk: {
    title: "Smerthnix - сайти для бізнесу від 2000 zł",
    description:
      "Створюю сучасні сайти для салонів, послуг і малого бізнесу. Вартість від 2000 zł: мобільна версія, Booksy, форми, SEO та додаткові функції.",
  },
  en: {
    title: "Smerthnix - business websites from PLN 2,000",
    description:
      "Modern websites for service businesses from PLN 2,000, including mobile layouts, Booksy, forms, SEO basics and additional features.",
  },
};

const translations = {
  ru: {
    skip: "Перейти к содержанию",
    brandRole: "разработка сайтов",
    navPortfolio: "Работа",
    navOffer: "Услуги",
    navPrice: "Цена",
    navProcess: "Как я работаю",
    navContact: "Написать",
    heroEyebrow: "Принимаю новые проекты",
    heroTitle: "Создаю сайты, которые понятно показывают бизнес и ведут клиента к контакту.",
    heroLead:
      "Для beauty-салонов, локальных услуг и малого бизнеса. Помогаю упорядочить предложение, вызвать доверие и связать сайт с Booksy, формой или другой системой.",
    heroPriceLabel: "Сайт для бизнеса",
    heroPrice: "от 2 000 zł",
    heroPriceNote: "точная цена после короткого разговора",
    heroPrimary: "Посмотреть работу",
    heroSecondary: "Написать в Telegram",
    heroNote: "Без длинной анкеты. Напишите, чем занимается бизнес и какой сайт вам нужен.",
    caseBadge: "Настоящий сайт в интернете",
    caseShort: "Студия массажа и SPA в Щецине",
    caseOpen: "Открыть сайт ↗",
    proofBooking: "запись и ваучеры",
    proofMobileTitle: "Телефон",
    proofMobile: "удобно на мобильном",
    trustPrice: "минимальный бюджет сайта",
    trustProject: "реальный проект онлайн",
    trustLanguages: "языка общения",
    trustDirectTitle: "Без посредников",
    trustDirect: "вы общаетесь прямо со мной",
    portfolioKicker: "Портфолио",
    portfolioTitle: "Я не показываю выдуманные макеты. Начнём с сайта, который уже работает.",
    caseImageLabel: "Посмотреть сайт ↗",
    caseType: "Сайт для бизнеса / beauty",
    caseLive: "работает",
    caseDescription:
      "Сайт упорядочивает большую услугу салона, передаёт атмосферу и ведёт клиента к записи в Booksy, покупке ваучера или контакту.",
    caseGoalLabel: "На сайте",
    caseGoal: "услуги, SPA-пакеты, ваучеры, отзывы и FAQ",
    caseIntegrationLabel: "Подключено",
    caseIntegration: "Booksy, Google Maps, Instagram и YouTube",
    caseResultLabel: "Важно",
    caseResult: "понятная мобильная версия и простой переход к записи",
    tagVouchers: "Ваучеры",
    tagReviews: "Отзывы",
    caseButton: "Посмотреть Fito Relax ↗",
    offerKicker: "Услуги",
    offerTitle: "Можно начать с простого сайта или добавить нужные функции.",
    offerLead:
      "Не нужно разбираться в технических словах. Достаточно объяснить, что клиент должен увидеть и сделать на сайте.",
    offerWebsiteTitle: "Сайт для компании",
    offerWebsiteText: "Предложение, услуги, фотографии, отзывы, контакты и мобильная версия.",
    offerWebsiteOne: "beauty-салон, кабинет или локальная услуга",
    offerWebsiteTwo: "одностраничный сайт или несколько страниц",
    offerWebsiteThree: "публикация на домене и базовое SEO",
    offerLandingTitle: "Продающая страница",
    offerLandingText: "Для одной услуги, курса, товара, мероприятия или рекламы.",
    offerLandingOne: "понятное предложение и сильный первый экран",
    offerLandingTwo: "кнопки, форма и контакты",
    offerLandingThree: "ответы на вопросы и элементы доверия",
    offerImproveTitle: "Улучшение готового сайта",
    offerImproveText: "Если сайт уже есть, но выглядит слабо, медленно работает или не приводит к контакту.",
    offerImproveOne: "новый вид и понятная структура",
    offerImproveTwo: "исправление мобильной версии",
    offerImproveThree: "добавление нужных функций",
    featuresKicker: "Возможности",
    featuresTitle: "Что можно добавить на сайт?",
    featuresLead: "Выбираем только то, что действительно нужно бизнесу и подходит по бюджету.",
    featureBooking: "Booksy и онлайн-запись",
    featurePrices: "цены и услуги",
    featureGallery: "галерея работ",
    featureReviews: "отзывы клиентов",
    featureVouchers: "ваучеры и подарочные карты",
    featurePayments: "онлайн-оплата",
    featureLanguages: "несколько языков",
    featureBlog: "блог и советы",
    featureFaq: "частые вопросы",
    featureMap: "карта и часы работы",
    featureForms: "формы и заявки",
    featureAnalytics: "статистика посещений",
    featureSeo: "базовое SEO",
    featureAutomation: "боты и автоматизация",
    priceKicker: "Цена",
    priceTitle: "Простой сайт начинается от 2 000 zł.",
    priceLead:
      "Итоговая цена зависит от количества страниц, языков, материалов и функций. До начала работы вы получаете понятный объём, цену и срок.",
    priceButton: "Получить расчёт",
    priceCardLabel: "Сайт для бизнеса",
    priceCardValue: "от 2 000 zł",
    priceItemOne: "дизайн под конкретный бизнес",
    priceItemTwo: "удобно на телефоне и компьютере",
    priceItemThree: "услуги, фотографии, отзывы и контакты",
    priceItemFour: "подключение домена и публикация",
    priceItemFive: "базовая подготовка для Google",
    priceItemSix: "согласованные правки",
    priceCardNote: "Дополнительные функции считаю отдельно до начала работы.",
    processKicker: "Как я работаю",
    processTitle: "Просто: определяем цель, я делаю сайт, вносим правки и публикуем.",
    processOneTitle: "Короткий разговор",
    processOneText: "Вы рассказываете о бизнесе, о том, что уже есть и что нужно получить.",
    processTwoTitle: "Объём и цена",
    processTwoText: "Согласовываем страницы, функции, срок, стоимость и материалы.",
    processThreeTitle: "Дизайн и разработка",
    processThreeText: "Я создаю сайт и показываю готовую версию для проверки.",
    processFourTitle: "Правки и запуск",
    processFourText: "Вношу согласованные изменения, проверяю сайт и подключаю домен.",
    contactKicker: "Контакт",
    contactTitle: "Коротко расскажите, какой сайт вам нужен.",
    contactLead:
      "Напишите название бизнеса, сферу и главную задачу сайта. Я отвечу, с чего лучше начать.",
    contactOne: "1. Чем занимается бизнес?",
    contactTwo: "2. Есть ли уже сайт или домен?",
    contactThree: "3. Какие функции нужны в первую очередь?",
    emailLabel: "Почта",
    contactNote: "Работаю удалённо с проектами по всей Польше.",
    footerRole: "сайты для бизнеса",
  },

  uk: {
    skip: "Перейти до змісту",
    brandRole: "створення сайтів",
    navPortfolio: "Робота",
    navOffer: "Послуги",
    navPrice: "Ціна",
    navProcess: "Як я працюю",
    navContact: "Написати",
    heroEyebrow: "Приймаю нові проєкти",
    heroTitle: "Створюю сайти, які зрозуміло показують бізнес і ведуть клієнта до контакту.",
    heroLead:
      "Для beauty-салонів, локальних послуг і малого бізнесу. Допомагаю впорядкувати пропозицію, викликати довіру та з'єднати сайт із Booksy, формою або іншою системою.",
    heroPriceLabel: "Сайт для бізнесу",
    heroPrice: "від 2 000 zł",
    heroPriceNote: "точна ціна після короткої розмови",
    heroPrimary: "Подивитися роботу",
    heroSecondary: "Написати в Telegram",
    heroNote: "Без довгої анкети. Напишіть, чим займається бізнес і який сайт вам потрібен.",
    caseBadge: "Справжній сайт онлайн",
    caseShort: "Студія масажу та SPA у Щецині",
    caseOpen: "Відкрити сайт ↗",
    proofBooking: "запис і ваучери",
    proofMobileTitle: "Телефон",
    proofMobile: "зручно на мобільному",
    trustPrice: "мінімальний бюджет сайту",
    trustProject: "реальний проєкт онлайн",
    trustLanguages: "мови спілкування",
    trustDirectTitle: "Без посередників",
    trustDirect: "ви спілкуєтеся прямо зі мною",
    portfolioKicker: "Портфоліо",
    portfolioTitle: "Я не показую вигадані макети. Почнімо із сайту, який уже працює.",
    caseImageLabel: "Подивитися сайт ↗",
    caseType: "Сайт для бізнесу / beauty",
    caseLive: "працює",
    caseDescription:
      "Сайт впорядковує велику пропозицію салону, передає атмосферу та веде клієнта до запису в Booksy, купівлі ваучера або контакту.",
    caseGoalLabel: "На сайті",
    caseGoal: "послуги, SPA-пакети, ваучери, відгуки та FAQ",
    caseIntegrationLabel: "Підключено",
    caseIntegration: "Booksy, Google Maps, Instagram і YouTube",
    caseResultLabel: "Важливо",
    caseResult: "зрозуміла мобільна версія та простий перехід до запису",
    tagVouchers: "Ваучери",
    tagReviews: "Відгуки",
    caseButton: "Подивитися Fito Relax ↗",
    offerKicker: "Послуги",
    offerTitle: "Можна почати з простого сайту або додати потрібні функції.",
    offerLead:
      "Не потрібно знати технічні слова. Достатньо пояснити, що клієнт має побачити та зробити на сайті.",
    offerWebsiteTitle: "Сайт для компанії",
    offerWebsiteText: "Пропозиція, послуги, фотографії, відгуки, контакти та мобільна версія.",
    offerWebsiteOne: "beauty-салон, кабінет або локальна послуга",
    offerWebsiteTwo: "односторінковий сайт або кілька сторінок",
    offerWebsiteThree: "публікація на домені та базове SEO",
    offerLandingTitle: "Сторінка для продажу",
    offerLandingText: "Для однієї послуги, курсу, товару, події або реклами.",
    offerLandingOne: "зрозуміла пропозиція та сильний перший екран",
    offerLandingTwo: "кнопки, форма та контакти",
    offerLandingThree: "відповіді на питання та елементи довіри",
    offerImproveTitle: "Покращення готового сайту",
    offerImproveText: "Якщо сайт уже є, але виглядає слабко, повільно працює або не веде до контакту.",
    offerImproveOne: "новий вигляд і зрозуміла структура",
    offerImproveTwo: "покращення мобільної версії",
    offerImproveThree: "додавання потрібних функцій",
    featuresKicker: "Можливості",
    featuresTitle: "Що можна додати на сайт?",
    featuresLead: "Обираємо лише те, що справді потрібно бізнесу та підходить за бюджетом.",
    featureBooking: "Booksy та онлайн-запис",
    featurePrices: "ціни та послуги",
    featureGallery: "галерея робіт",
    featureReviews: "відгуки клієнтів",
    featureVouchers: "ваучери та подарункові картки",
    featurePayments: "онлайн-оплата",
    featureLanguages: "кілька мов",
    featureBlog: "блог і поради",
    featureFaq: "часті питання",
    featureMap: "карта та години роботи",
    featureForms: "форми та заявки",
    featureAnalytics: "статистика відвідувань",
    featureSeo: "базове SEO",
    featureAutomation: "боти й автоматизація",
    priceKicker: "Ціна",
    priceTitle: "Простий сайт починається від 2 000 zł.",
    priceLead:
      "Підсумкова ціна залежить від кількості сторінок, мов, матеріалів і функцій. До початку роботи ви отримуєте зрозумілий обсяг, ціну та термін.",
    priceButton: "Отримати розрахунок",
    priceCardLabel: "Сайт для бізнесу",
    priceCardValue: "від 2 000 zł",
    priceItemOne: "дизайн під конкретний бізнес",
    priceItemTwo: "зручно на телефоні та комп'ютері",
    priceItemThree: "послуги, фотографії, відгуки та контакти",
    priceItemFour: "підключення домену та публікація",
    priceItemFive: "базова підготовка для Google",
    priceItemSix: "узгоджені правки",
    priceCardNote: "Додаткові функції рахую окремо до початку роботи.",
    processKicker: "Як я працюю",
    processTitle: "Просто: визначаємо мету, я роблю сайт, вносимо правки та публікуємо.",
    processOneTitle: "Коротка розмова",
    processOneText: "Ви розповідаєте про бізнес, про те, що вже є, і що потрібно отримати.",
    processTwoTitle: "Обсяг і ціна",
    processTwoText: "Узгоджуємо сторінки, функції, термін, вартість і матеріали.",
    processThreeTitle: "Дизайн і розробка",
    processThreeText: "Я створюю сайт і показую готову версію для перевірки.",
    processFourTitle: "Правки та запуск",
    processFourText: "Вношу узгоджені зміни, перевіряю сайт і підключаю домен.",
    contactKicker: "Контакт",
    contactTitle: "Коротко розкажіть, який сайт вам потрібен.",
    contactLead: "Напишіть назву бізнесу, сферу та головне завдання сайту. Я відповім, з чого краще почати.",
    contactOne: "1. Чим займається бізнес?",
    contactTwo: "2. Чи є вже сайт або домен?",
    contactThree: "3. Які функції потрібні насамперед?",
    emailLabel: "Пошта",
    contactNote: "Працюю віддалено з проєктами по всій Польщі.",
    footerRole: "сайти для бізнесу",
  },

  en: {
    skip: "Skip to content",
    brandRole: "business websites",
    navPortfolio: "Work",
    navOffer: "Services",
    navPrice: "Price",
    navProcess: "Process",
    navContact: "Contact",
    heroEyebrow: "Available for new projects",
    heroTitle: "I build websites that explain a business clearly and lead visitors to contact.",
    heroLead:
      "For beauty salons, local services and small businesses. I organise the offer, build trust and connect the website to Booksy, a form or another system.",
    heroPriceLabel: "Business website",
    heroPrice: "from PLN 2,000",
    heroPriceNote: "exact price after a short call",
    heroPrimary: "View live project",
    heroSecondary: "Message on Telegram",
    heroNote: "No long questionnaire. Tell me what the business does and what the website should achieve.",
    caseBadge: "Real project online",
    caseShort: "Massage and SPA studio in Szczecin",
    caseOpen: "Open website ↗",
    proofBooking: "booking and vouchers",
    proofMobileTitle: "Mobile",
    proofMobile: "clear on a phone",
    trustPrice: "minimum website budget",
    trustProject: "real live project",
    trustLanguages: "communication languages",
    trustDirectTitle: "No middlemen",
    trustDirect: "work directly with me",
    portfolioKicker: "Portfolio",
    portfolioTitle: "No fictional mockups. Start with a website that is already live.",
    caseImageLabel: "View live website ↗",
    caseType: "Business website / beauty",
    caseLive: "live",
    caseDescription:
      "The website organises a broad salon offer, presents the atmosphere and leads visitors to Booksy booking, vouchers or direct contact.",
    caseGoalLabel: "Website",
    caseGoal: "services, SPA packages, vouchers, reviews and FAQ",
    caseIntegrationLabel: "Connected",
    caseIntegration: "Booksy, Google Maps, Instagram and YouTube",
    caseResultLabel: "Focus",
    caseResult: "clear mobile layout and an easy path to booking",
    tagVouchers: "Vouchers",
    tagReviews: "Reviews",
    caseButton: "View Fito Relax ↗",
    offerKicker: "Services",
    offerTitle: "Start with a simple website or add the features your business needs.",
    offerLead:
      "You do not need technical terminology. Tell me what the visitor should see and what action they should take.",
    offerWebsiteTitle: "Business website",
    offerWebsiteText: "Offer, services, photos, reviews, contact and a mobile layout.",
    offerWebsiteOne: "beauty salon, practice or local service",
    offerWebsiteTwo: "one-page website or several pages",
    offerWebsiteThree: "domain launch and basic SEO",
    offerLandingTitle: "Sales landing page",
    offerLandingText: "For one service, course, product, event or advertising campaign.",
    offerLandingOne: "clear offer and strong first screen",
    offerLandingTwo: "buttons, forms and contact details",
    offerLandingThree: "FAQ and trust elements",
    offerImproveTitle: "Existing website improvement",
    offerImproveText: "For a site that looks weak, runs slowly or does not lead visitors to contact.",
    offerImproveOne: "fresh design and clearer structure",
    offerImproveTwo: "better mobile layout",
    offerImproveThree: "missing features added",
    featuresKicker: "Options",
    featuresTitle: "What can be added to the website?",
    featuresLead: "We choose only what makes sense for the business and the budget.",
    featureBooking: "Booksy and online booking",
    featurePrices: "services and price list",
    featureGallery: "work gallery",
    featureReviews: "customer reviews",
    featureVouchers: "vouchers and gift cards",
    featurePayments: "online payments",
    featureLanguages: "multiple languages",
    featureBlog: "blog and guides",
    featureFaq: "FAQ",
    featureMap: "map and opening hours",
    featureForms: "forms and enquiries",
    featureAnalytics: "visitor analytics",
    featureSeo: "basic SEO",
    featureAutomation: "bots and automation",
    priceKicker: "Price",
    priceTitle: "A simple business website starts from PLN 2,000.",
    priceLead:
      "The final price depends on the number of pages, languages, materials and features. Before work starts, you receive a clear scope, price and delivery date.",
    priceButton: "Request a quote",
    priceCardLabel: "Business website",
    priceCardValue: "from PLN 2,000",
    priceItemOne: "design tailored to the business",
    priceItemTwo: "clear on mobile and desktop",
    priceItemThree: "offer, photos, reviews and contact",
    priceItemFour: "domain setup and launch",
    priceItemFive: "basic preparation for Google",
    priceItemSix: "agreed revision round",
    priceCardNote: "Additional features are quoted before work begins.",
    processKicker: "Process",
    processTitle: "Simple: define the goal, build, review and launch.",
    processOneTitle: "Short conversation",
    processOneText: "Tell me what the business does, what already exists and what you need.",
    processTwoTitle: "Scope and price",
    processTwoText: "We agree on pages, features, schedule, price and materials.",
    processThreeTitle: "Design and build",
    processThreeText: "I build the website and share a complete version for review.",
    processFourTitle: "Revisions and launch",
    processFourText: "I apply the agreed changes, test the website and connect the domain.",
    contactKicker: "Contact",
    contactTitle: "Tell me briefly what kind of website you need.",
    contactLead: "Send the business name, industry and main website goal. I will suggest the best starting point.",
    contactOne: "1. What does the business do?",
    contactTwo: "2. Do you already have a website or domain?",
    contactThree: "3. Which features matter most?",
    emailLabel: "Email",
    contactNote: "Remote cooperation is available across Poland.",
    footerRole: "business websites",
  },
};

const basePolish = new Map();
document.querySelectorAll("[data-i18n]").forEach((element) => {
  basePolish.set(element.dataset.i18n, element.textContent.trim());
});

function setLanguage(language) {
  const lang = ["pl", "ru", "uk", "en"].includes(language) ? language : "pl";
  const dictionary = translations[lang] || {};

  document.documentElement.lang = lang;
  document.title = pageMeta[lang].title;
  document.getElementById("meta-description").setAttribute("content", pageMeta[lang].description);

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    element.textContent = lang === "pl" ? basePolish.get(key) : dictionary[key] || basePolish.get(key);
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.setAttribute("aria-pressed", String(button.dataset.lang === lang));
  });

  localStorage.setItem("portfolio-language", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.12 },
);

document.querySelectorAll(".reveal").forEach((element) => observer.observe(element));
document.getElementById("year").textContent = new Date().getFullYear();

setLanguage(localStorage.getItem("portfolio-language") || "pl");
